import type { IconAgencyTemplateContent } from "@/content/icon-agency-template";

export const upscaleApplovinCreativeOsContent = {
  templateNotice:
    "UPSCALE DEMO · V1.3 · APPLOVIN CREATIVE OS · ICON-STRUCTURED MOBILE LANDING PAGE · ALL BRACKETED COPY REQUIRES INPUT",
  brand: { name: "upscale.ai", descriptor: "AppLovin Creative OS" },
  navigation: { login: "[UTILITY LINK]", primaryCta: "Start My First Batch" },
  hero: {
    eyebrow: "AppLovin Creative OS · v1.3",
    headline: "Creative OS",
    subheadline:
      "12 new AppLovin ads every month, built from ads and assets you already have.",
    description:
      "We review your winners, create briefs, and draft four ads for approval every 10 days.",
    positioningLine:
      "Approve batch one before paying. Launch into AppLovin within one week.",
    primaryCta: "Start My First Batch",
    secondaryCta: "See Example Ads",
    assurances: [
      "[APPROVED GUARANTEE OR CANCELLATION LANGUAGE]",
      "Launch within one week",
      "[VERIFIED PROOF POINT]",
    ],
  },
  creativeExamples: [
    {
      eyebrow: "Branch",
      title: "Branch vertical creative",
      detail: "AppLovin · 9:16",
      image: "/customer-assets/wall-branch.jpg",
      alt: "Branch vertical creative frame sourced from the Upscale AppLovin page",
    },
    {
      eyebrow: "Jones Road",
      title: "Jones Road vertical creative",
      detail: "AppLovin · 9:16",
      image: "/customer-assets/wall-jones-road.jpg",
      alt: "Jones Road vertical creative frame sourced from the Upscale AppLovin page",
    },
  ],
  customerLogos: [
    { name: "Westmore Beauty", image: "/customer-assets/logo-westmore.png" },
    { name: "Legion Athletics", image: "/customer-assets/logo-legion.png" },
    { name: "Biom", image: "/customer-assets/logo-biom.png" },
    { name: "David Protein", image: "/customer-assets/logo-david.png" },
    { name: "Fast Growing Trees", image: "/customer-assets/logo-fast-growing-trees.png" },
  ],
  gateways: [
    { label: "Creative Formats", kicker: "[FORMAT COUNT] starting points", href: "#formats", tone: "bg-[#00f0ff]" },
    { label: "Story", kicker: "[WHY UPSCALE EXISTS]", href: "#story", tone: "bg-[#dcdcf8]" },
    { label: "Investors / Advisors", kicker: "[CREDIBILITY SOURCE]", href: "#investors", tone: "bg-[#efd9ed]" },
    { label: "Partner Program", kicker: "[PARTNER ECONOMICS]", href: "#partners", tone: "bg-[#d5f6f7]" },
    { label: "Creative OS", kicker: "[MODULE COUNT] product modules", href: "#admaker", tone: "bg-[#d6eaf0]" },
    { label: "Us vs. Them", kicker: "[COMPARISON FRAME]", href: "#comparison", tone: "bg-[#eceff0]" },
    { label: "Customers", kicker: "[CUSTOMER PROOF]", href: "#customers", tone: "bg-[#dcebed]" },
    { label: "Workflow", kicker: "[STEP COUNT] visible handoffs", href: "#process", tone: "bg-[#e1dff8]" },
  ],
  formats: {
    eyebrow: "Creative Formats",
    title: "[FORMAT-LIBRARY PROMISE]",
    description: "[EXPLAIN HOW UPSCALE SELECTS, PRODUCES, OR MANAGES APPLOVIN CREATIVE FORMATS.]",
    items: [
      { name: "[FORMAT 01]", hook: "[HOOK PATTERN 01]", note: "[WHEN AND WHY TO USE THIS FORMAT]", tone: "bg-[#00f0ff]" },
      { name: "[FORMAT 02]", hook: "[HOOK PATTERN 02]", note: "[WHEN AND WHY TO USE THIS FORMAT]", tone: "bg-[#d5f6f7]" },
      { name: "[FORMAT 03]", hook: "[HOOK PATTERN 03]", note: "[WHEN AND WHY TO USE THIS FORMAT]", tone: "bg-[#d6eaf0]" },
      { name: "[FORMAT 04]", hook: "[HOOK PATTERN 04]", note: "[WHEN AND WHY TO USE THIS FORMAT]", tone: "bg-[#dcdcf8]" },
    ],
  },
  process: {
    eyebrow: "How it works",
    title: "From AppLovin connection to approved ads",
    description: "The complete seven-step operating plan",
    steps: [
      { title: "Connect AppLovin", description: "Connect your AppLovin account and [APPROVED ASSET SOURCE(S)].", timing: "[TIMING]" },
      { title: "Review winners and assets", description: "Review [ACCOUNT DATA], winning ads and approved assets.", timing: "[TIMING]" },
      { title: "Generate creative briefs", description: "Generate [BRIEF COUNT] creative briefs for acceptance.", timing: "[TIMING]" },
      { title: "Approve briefs", description: "Accept the briefs that should move into production.", timing: "[TIMING]" },
      { title: "Draft and approve ads", description: "The AI editor drafts [DRAFT COUNT] ads for review and [REVISION PROCESS].", timing: "[TIMING]" },
      { title: "Approve batch one and pay", description: "Pay after approving the first batch, then continue month to month.", timing: "[TIMING]" },
      { title: "Launch into AppLovin", description: "Launch approved ads into [APPLOVIN ACCOUNT / CAMPAIGN DESTINATION].", timing: "Within one week" },
    ],
  },
  pricing: {
    eyebrow: "Pricing / Engagement",
    title: "[COMMERCIAL MODEL HEADLINE]",
    description: "[STATE WHAT STARTS NOW, WHEN PAYMENT BEGINS, AND WHICH OPTION FITS WHICH CUSTOMER.]",
    tiers: [
      {
        name: "[ENTRY OFFER]",
        price: "[PRICE]",
        cadence: "[BILLING TRIGGER / CADENCE]",
        description: "[EXACT ENTRY-PACKAGE SCOPE]",
        bullets: ["[DELIVERABLE 01]", "[DELIVERABLE 02]", "[DELIVERY WINDOW]", "[RIGHTS / TERMS]"],
        cta: "[PRIMARY CTA]",
        featured: true,
        action: "start",
      },
      {
        name: "[HIGH-TOUCH OFFER]",
        price: "[PRICE]",
        cadence: "[CADENCE]",
        description: "[EXACT HIGH-TOUCH SCOPE]",
        bullets: ["[DELIVERABLE 01]", "[DELIVERABLE 02]", "[SUPPORT LEVEL]", "[TERMS]"],
        cta: "[SECONDARY CTA]",
        action: "director",
      },
      {
        name: "[ENTERPRISE / PARTNER OFFER]",
        price: "[PRICE]",
        cadence: "[CADENCE]",
        description: "[EXACT ENTERPRISE OR PARTNER SCOPE]",
        bullets: ["[DELIVERABLE 01]", "[DELIVERABLE 02]", "[SUPPORT LEVEL]", "[TERMS]"],
        cta: "[ENTERPRISE CTA]",
        action: "director",
      },
    ],
    doneForYou: ["[SERVICE 01]", "[SERVICE 02]", "[SERVICE 03]", "[SERVICE 04]", "[SERVICE 05]"],
    riskFree: ["[RISK REVERSAL]", "[BILLING NOTICE]", "[REFUND OR REVISION POLICY]", "[DATA / ASSET OWNERSHIP]", "[DELIVERY SLA]"],
  },
  customers: {
    eyebrow: "Customers",
    title: "[CUSTOMER STORY COUNT] stories from [BRAND COUNT] brands.",
    description: "[CUSTOMER-PROOF THESIS. USE ONLY APPROVED, ATTRIBUTED EVIDENCE.]",
    stats: [
      { value: "[##]", label: "customer stories" },
      { value: "[##+]", label: "brands served" },
      { value: "[##]", label: "primary proof metric" },
    ],
    stories: [
      { name: "[CUSTOMER 01]", category: "[SEGMENT]", quote: "[APPROVED CUSTOMER QUOTE]", result: "[VERIFIED RESULT + TEST WINDOW]", tone: "bg-[#efd9ed]" },
      { name: "[CUSTOMER 02]", category: "[SEGMENT]", quote: "[APPROVED CUSTOMER QUOTE]", result: "[VERIFIED RESULT + ATTRIBUTION]", tone: "bg-[#00f0ff]" },
      { name: "[CUSTOMER 03]", category: "[SEGMENT]", quote: "[APPROVED CUSTOMER QUOTE]", result: "[VERIFIED RESULT + SAMPLE SIZE]", tone: "bg-[#d5f6f7]" },
    ],
  },
  products: {
    eyebrow: "AppLovin Creative OS",
    title: "[PRODUCT-SYSTEM HEADLINE]",
    description: "[EXPLAIN HOW THE MODULES WORK TOGETHER WITHOUT CLAIMING UNSUPPLIED CAPABILITIES.]",
    items: [
      { name: "[MODULE 01]", label: "[FUNCTION]", description: "[MODULE DESCRIPTION]", ui: ["[STATE 01]", "[STATE 02]", "[STATE 03]"], tone: "bg-[#00f0ff]" },
      { name: "[MODULE 02]", label: "[FUNCTION]", description: "[MODULE DESCRIPTION]", ui: ["[STATE 01]", "[STATE 02]", "[STATE 03]"], tone: "bg-[#dcdcf8]" },
      { name: "[MODULE 03]", label: "[FUNCTION]", description: "[MODULE DESCRIPTION]", ui: ["[STATE 01]", "[STATE 02]", "[STATE 03]"], tone: "bg-[#d6eaf0]" },
      { name: "[MODULE 04]", label: "[FUNCTION]", description: "[MODULE DESCRIPTION]", ui: ["[STATE 01]", "[STATE 02]", "[STATE 03]"], tone: "bg-[#d5f6f7]" },
    ],
  },
  comparison: {
    eyebrow: "Us vs. them",
    title: "[CATEGORY-COMPARISON HEADLINE]",
    description: "[DEFINE THE ALTERNATIVES AND THE DECISION CRITERIA.]",
    columns: ["Upscale", "[ALT 01]", "[ALT 02]", "[ALT 03]", "[ALT 04]", "[ALT 05]", "[ALT 06]", "[ALT 07]"],
    rows: [
      { feature: "[DIMENSION 01]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[DIMENSION 02]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[DIMENSION 03]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[DIMENSION 04]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[DIMENSION 05]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[DIMENSION 06]", values: ["[VALUE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
      { feature: "[ENTRY PRICE]", values: ["[PRICE]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"] },
    ],
    footnote: "Every competitive capability, price, and claim must be verified immediately before publication.",
  },
  founder: {
    eyebrow: "Upscale team",
    title: "Meet the team behind Creative OS",
    story: "[APPROVED EXECUTIVE TEAM STORY AND VERIFIED OUTCOME]",
    quote: "[APPROVED TEAM OR FOUNDER QUOTE]",
    attribution: "[APPROVED ATTRIBUTION]",
    milestones: ["[EARLY INSIGHT]", "[VERIFIED EXPERIENCE]", "[VERIFIED OUTCOME]", "[WHY UPSCALE NOW]"],
  },
  investors: {
    eyebrow: "Investors / Advisors",
    title: "Backed by NVP, M12 and Eniac",
    description: "[APPROVED INVESTOR CONTEXT]",
    names: ["NVP", "M12", "Eniac"],
  },
  partner: {
    eyebrow: "Partner Program",
    title: "Earn [BOUNTY] plus [REVENUE SHARE].",
    description: "[PARTNER ICP, QUALIFICATION RULES, PAYOUT TRIGGER, AND PROGRAM VALUE.]",
    bounty: "[BOUNTY]",
    revenueShare: "[REV SHARE]",
    steps: ["[PARTNER STEP 01]", "[PARTNER STEP 02]", "[PARTNER STEP 03]", "[PARTNER STEP 04]"],
    formats: ["[POST FORMAT 01]", "[POST FORMAT 02]", "[POST FORMAT 03]", "[POST FORMAT 04]"],
    cta: "[PARTNER CTA]",
  },
  noveltyPricing: {
    eyebrow: "Creative OS 3.0",
    title: "[PLAYFUL PATTERN-BREAK HEADLINE]",
    description: "[OPTIONAL TONAL RESET BEFORE THE FINAL CTA. REMOVE IF IT DOES NOT FIT UPSCALE.]",
    items: [
      { name: "[PLAYFUL PLAN 01]", price: "[PRICE]", note: "[ABSURD OR SELF-AWARE PLAN DESCRIPTION]", tone: "bg-[#00f0ff]" },
      { name: "[PLAYFUL PLAN 02]", price: "[PRICE]", note: "[ABSURD OR SELF-AWARE PLAN DESCRIPTION]", tone: "bg-[#dcdcf8]" },
    ],
  },
  explore: {
    eyebrow: "Explore more",
    title: "[REOPEN THE HIGHEST-INTENT BRANCHES]",
    items: [
      { label: "Creative Formats", description: "[FORMAT-LIBRARY VALUE]", href: "#formats" },
      { label: "Founder Story", description: "[FOUNDER-STORY VALUE]", href: "#story" },
      { label: "Customers", description: "[CUSTOMER-PROOF VALUE]", href: "#customers" },
      { label: "Creative OS", description: "[PRODUCT-MODULE VALUE]", href: "#admaker" },
      { label: "Us vs. Them", description: "[COMPARISON VALUE]", href: "#comparison" },
      { label: "Partner Program", description: "[PARTNER VALUE]", href: "#partners" },
    ],
  },
  finalCta: {
    eyebrow: "AppLovin Creative OS",
    title: "[FINAL PRIMARY PROMISE]",
    description: "[APPROVED GUARANTEE OR CANCELLATION LANGUAGE]",
    primaryCta: "Start My First Batch",
    secondaryCta: "See Example Ads",
  },
  dialogs: {
    start: {
      title: "Start your first AppLovin batch",
      description: "Enter your work email. We will use the company domain to begin [APPROVED QUALIFICATION AND ROUTING].",
      button: "Continue to scheduling",
      successTitle: "Choose the next step",
      successDescription: "Continue to [APPROVED ONBOARDING OR SCHEDULER].",
    },
    director: {
      title: "[HIGH-TOUCH PATH]",
      description: "[EXPLAIN WHO THIS PATH IS FOR AND WHAT THE CONVERSATION COVERS.]",
      button: "[SUBMIT CTA]",
      successTitle: "[SUCCESS STATE TITLE]",
      successDescription: "[SUCCESS STATE NEXT STEP]",
    },
  },
} satisfies IconAgencyTemplateContent;
